"""Report agent — assembles final Markdown deliverable."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..state import PIAState


def report_node(state: PIAState) -> dict[str, Any]:
    """Compile all outputs into a single Markdown report."""
    run_dir = Path(state["run_dir"])

    forecast = state.get("forecast_results", {})
    risk = state.get("risk_scores", {})
    strategy = state.get("strategy_recommendations", "")

    log: list[str] = ["Report: compiling final deliverable..."]

    # Build report
    lines = [
        "# Procurement Intelligence Report",
        "",
        f"**Run ID:** {state['run_id']}",
        f"**Dataset:** {state['data_path']}",
        "",
        "---",
        "",
        "## 1. Supplier Overview",
        "",
        "| Supplier | Country | Category | Orders | Avg Lead Time (days) |",
        "|----------|---------|----------|--------|----------------------|",
    ]

    for sid, f in forecast.items():
        lines.append(
            f"| {f['supplier_name']} | {risk.get(sid, {}).get('country', 'N/A')} | "
            f"{risk.get(sid, {}).get('category', 'N/A')} | {f['order_count']} | {f['avg_lead_time']} |"
        )

    lines.extend([
        "",
        "## 2. Risk Assessment",
        "",
        "| Supplier | Risk Level | Risk Score | Spend Share % | Predicted Next Delay |",
        "|----------|------------|------------|---------------|----------------------|",
    ])

    for sid, r in risk.items():
        f = forecast.get(sid, {})
        lines.append(
            f"| {r['supplier_name']} | **{r['risk_level']}** | {r['total_risk_pct']}/100 | "
            f"{r['spend_share_pct']}% | {f.get('predicted_next_delay', 'N/A')} days |"
        )

    lines.extend([
        "",
        "## 3. Strategic Recommendations",
        "",
        strategy,
        "",
        "---",
        "",
        "*Generated by Procurement Intelligence Agent (PIA)*",
    ])

    report_md = "\n".join(lines)
    report_path = run_dir / "report.md"
    report_path.write_text(report_md, encoding="utf-8")

    log.append(f"Report saved to {report_path}")

    return {
        "report_md": report_md,
        "report_path": str(report_path),
        "log": log,
    }
